BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Todo] (
    [id] INT NOT NULL IDENTITY(1,1),
    [todo] NVARCHAR(100) NOT NULL,
    [completed] BIT NOT NULL CONSTRAINT [DF__Todo__completed] DEFAULT 0,
    CONSTRAINT [PK__Todo__id] PRIMARY KEY ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN 
    ROLLBACK TRAN;
END;
THROW

END CATCH
